/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package luftballons;

/**
 *
 * @author MAGO_PC
 */
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class HPaneel extends javax.swing.JPanel {

    private int x, y;
    private int g;
    private Ballon ballons[] = new Ballon[4];
    private JLabel bogen;
    private JLabel punkte_lbl;
    private JLabel punkteInfo_lbl;
    private JLabel spanisch_lbl;
    private JLabel spanischInfo_lbl;
    private Tracker trck;
    ExecutorService threadPool = Executors.newCachedThreadPool();
    

    /**
     * Creates new form hPaneel
     * @param behaelter
     * @param kategorie
     */
    public HPaneel(Container behaelter, int kategorie) {
        behaelter.setSize(800,1000);
        behaelter.validate();
        initComponents();
        addMouseMotionListener(new Oyente());
        addMouseListener(new Zuhoerer());
        setLayout(null);
        setBackground(Color.WHITE);
        bogen = new JLabel();
        bogen.setSize(80, 80);
        bogen.setIcon(new ImageIcon(getClass().getResource("/bilder/bow.png")));
        add(bogen);
        bogen.setLocation(200, 850);
        repaint();        
        ballons[0] = new Ballon(Ballon.zufaelling(0, 100), 50);
        ballons[1] = new Ballon(Ballon.zufaelling(300, 500), 50);
        ballons[2] = new Ballon(Ballon.zufaelling(0, 100), 180);
        ballons[3] = new Ballon(Ballon.zufaelling(300, 500), 180);
        g = 50;
        punkte_lbl = new JLabel("PUNTOS: ");
        punkteInfo_lbl = new JLabel("0");
        punkte_lbl.setFont(new java.awt.Font("Arial", 1, 14));
        punkteInfo_lbl.setFont(new java.awt.Font("Arial", 1, 14));
        punkte_lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        punkteInfo_lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JPanel topPaneel = new JPanel(new FlowLayout());
        topPaneel.setBackground(Color.WHITE);
        topPaneel.add(punkte_lbl);
        topPaneel.add(punkteInfo_lbl);

        spanisch_lbl = new JLabel("PALABRA A BUSCAR: ");
        spanischInfo_lbl = new JLabel("");
        spanisch_lbl.setFont(new java.awt.Font("Arial", 1, 14));
        spanischInfo_lbl.setFont(new java.awt.Font("Arial", 1, 14));
        spanisch_lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        spanischInfo_lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JPanel unterPaneel = new JPanel(new FlowLayout());
        unterPaneel.setBackground(Color.WHITE);
        unterPaneel.add(spanisch_lbl);
        unterPaneel.add(spanischInfo_lbl);

        for (int i = 0; i < ballons.length; i++) {
            add(ballons[i]);
            Thread t = new Thread(ballons[i]);
            threadPool.execute(t);
          }

        behaelter.add(topPaneel, BorderLayout.NORTH);
        behaelter.add(unterPaneel, BorderLayout.SOUTH);
        trck = new Tracker(ballons, punkteInfo_lbl, spanischInfo_lbl, kategorie, behaelter);
        Thread tt = new Thread(trck);
        threadPool.execute(tt);
     }

    private class Oyente extends MouseAdapter {

        @Override
        public void mouseMoved(MouseEvent evt) {
            x = evt.getX();
            y = bogen.getY();
            if (x <= 480) {
                bogen.setLocation((x - 35), y);
                repaint();
            }
        }
    }

    private class Zuhoerer implements MouseListener {

        @Override
        public void mouseClicked(MouseEvent e) {
            if (trck.getPfeilON()) {
                Kanone k = new Kanone(bogen.getX() + 35, 610, g);
                add(k);
                repaint();
                Thread tPfeil = new Thread(k);
                tPfeil.start();
                trck.setKanone(k, false);
            }
        }

        @Override
        public void mousePressed(MouseEvent e) {

        }

        @Override
        public void mouseReleased(MouseEvent e) {

        }

        @Override
        public void mouseEntered(MouseEvent e) {

        }

        @Override
        public void mouseExited(MouseEvent e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
